### ISSUE TITLE
Issue when not using Dark Theme

### ISSUE THREAD

**Issue by ich777** [jqshuv/jqshuv#2]
Hi,
I think this is not what you want or am I wrong:
![image](https://user-images.githubusercontent.com/28066518/189587583-043ac08e-d183-4865-a2e5-7232074e1d76.png)

I know that it says it looks better in Dark Mode but Dark Mode is not my preferred choice because Dark Mode is not always superior over the default white theme.

**Comment by jqshuv** [comment]
Hmm, I see, I'll look into that...

**Comment by ich777** [comment]
> Hmm, I see, I'll look into that...

Not a real issue in any way, just a friendly heads up... :)
Maybe a more greyish color will solve this maybe?
Closing this issue because it's not an issue.
